spring:
  application:
    name: jira-lite # spring project name
  jackson:
    serialization:
      write-dates-as-timestamps: false # write dates as timestamps

server:
  port: ${SERVER_PORT:8080} # server port
  servlet:
    context-path: /api

app:
  s3:
    bucket: ${S3_BUCKET:jira-lite-attachments}
    region: ${AWS_REGION:ap-southeast-2}
    upload-expiry-seconds: ${S3_UPLOAD_EXPIRY_SECONDS:300}
    download-expiry-seconds: ${S3_DOWNLOAD_EXPIRY_SECONDS:300}

# Note:
# - Do not hardcode local DB settings here.
# - Use profile "local" to run with local Postgres.

